include: package:flutter_lints/flutter.yaml
# analysis_options.yaml
analyzer:
  # Other rules...

# Official Dart formatter settings
linter:
  rules:
    # Other lint rules...

dart_format:
  line_length: 40 # The default is 80. Try a lower value if you prefer.