name: Build App [dev]

on:
  push:
    tags:
      - "v*-dev*"
    branches:
      - master

jobs:
  build:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Create Release for Tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/release/app-release.apk
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          prerelease: true
          token: ${{ secrets.TOKEN }}

      - name: Update Latest Dev Release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/release/app-release.apk
          tag: 'latest-dev'
          name: 'Latest Development Build (master)'
          allowUpdates: true
          prerelease: true
          token: ${{ secrets.TOKEN }}